tasks:
  - init: make install
    command: make config
vscode:
  extensions:
    - ms-vscode-remote.remote-containers
    - usernamehw.errorlens
    - gitpod.gitpod-desktop
    - ms-toolsai.jupyter-keymap
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode-remote.vscode-remote-extensionpack
    - ms-vscode-remote.remote-wsl
    - ms-azuretools.vscode-docker
    - donjayamanne.githistory
    - GitHub.copilot-nightly
    - GitHub.vscode-pull-request-github
    - eamodio.gitlens
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - ms-vscode.makefile-tools
    - DavidAnson.vscode-markdownlint
    - ms-python.vscode-pylance
    - ms-python.python
    - redhat.vscode-yaml
